services:
    client:
        build: ./client
        ports:
            - "80:3000"
    server:
        build: ./server
        ports:
            - "8080:8080"
            - "8081:8081"
    database:
        build: ./db
        ports:
            - "27017:27017"
